###############################################################################
# LEGALESE:   "Copyright (C) 2019-2020, Celestica Corp. All rights reserved." #
#                                                                             #
# This source code is confidential, proprietary, and contains trade           #
# secrets that are the sole property of Celestica Corp.                       #
# Copy and/or distribution of this source code or disassembly or reverse      #
# engineering of the resultant object code are strictly forbidden without     #
# the written consent of Celestica Corp.                                      #
#                                                                             #
###############################################################################
powerCycler1:
    userName  : wedge400
    password  : '123456'
    product   : powercycler
    managementIP : 10.204.112.53
    managementPort : '23'
    managementPrompt : 'apc>'
    platformType : Schneider Electric

powerCycler2:
    userName  : w400c
    password  : '123456'
    product   : powercycler
    managementIP : 10.204.112.54
    managementPort : '23'
    managementPrompt : 'apc>'
    platformType : Schneider Electric

powerCycler3:
    userName  : wedge400
    password  : '123456'
    product   : powercycler
    managementIP : 10.204.112.57
    managementPort : '23'
    managementPrompt : 'apc>'
    platformType : Schneider Electric

powerCycler4:
    userName  : wedge400c
    password  : test
    product   : powercycler
    managementIP : 10.204.112.55
    managementPort : '23'
    managementPrompt : 'apc>'
    platformType : Schneider Electric
