
###############################################################################
# LEGALESE:   "Copyright (C) 2019-2020, Celestica Corp. All rights reserved." #
#                                                                             #
# This source code is confidential, proprietary, and contains trade           #
# secrets that are the sole property of Celestica Corp.                       #
# Copy and/or distribution of this source code or disassembly or reverse      #
# engineering of the resultant object code are strictly forbidden without     #
# the written consent of Celestica Corp.                                      #
#                                                                             #
###############################################################################
BMC:
    name            :  BMC
    hostImageDir    : /home/automation/Auto_Test/automation/FB-Minipack3/autotest/BMC # the image location on the server
    isAutoBuild     : false             # it is auto build, Jenkins task will put the new built images under hostImageDir
    imageInfoFile   : ImageInfo.yaml   # for the auto build, Jenkins task will update the fw information in this file, and CAP script will parse fw information from this file.
    localImageDir   : /mnt/data1/BMC   # the image location on the test unit
    imageServer     : PC               # the server contain the images, it is defined in DeviceInfo.yaml
    oldImage        : ''
    newImage        : ''
    oldVersion      : ''
    newVersion      : ''



BIOS:
    name            :  BIOS
    hostImageDir    : /home/automation/Auto_Test/automation/FB-Minipack3/autotest/BIOS
    isAutoBuild     : false      # it is not auto build, user need put the images under hostImageDir manually, and update the fw information in this file
    imageInfoFile    : none       # it is not auto build, no imageInfoFile, CAP script will use the information defined in this file
    localImageDir   : /tmp
    imageServer     : PC
    oldImage        : 'NL302.bin'
    newImage        : 'NL302.bin'
    oldVersion      : NL302
    newVersion      : NL302

COME_CPLD:
    name            : COME_CPLD
    hostImageDir    : /home/automation/Auto_Test/automation/FB-Minipack3/autotest/CPLD
    isAutoBuild     : false
    imageInfoFile   : none
    localImageDir   : /mnt/data/COME_CPLD
    imageServer     : PC
    oldImage        : 'NL_FPGA_E04.jbc'
    newImage        : 'NL_FPGA_301.jbc'
    oldVersion      : 'E04'
    newVersion      : '301'



CPLD:
    name            :  CPLD
    hostImageDir    : /home/automation/Auto_Test/automation/FB-Minipack3/autotest/CPLD
    isAutoBuild     : false
    imageInfoFile   : none
    localImageDir   : '/var/unidiag/firmware'
    imageServer     : PC
    oldImage        :
        fcm         : 'WEDGE400C_FAN_CPLD_v4p1.jed'
        scm         : 'WEDGE400C_SCM_CPLD_vfpf.jed'
        smb         : 'WEDGE400C_SMB_CPLD_v2p2.jed'
        pwr         : 'WEDGE400C_PWR_CPLD_v2p3.jed'
    newImage        :
        fcm         : 'WEDGE400C_FAN_CPLD_v4p2.jed'
        scm         : 'WEDGE400C_SCM_CPLD_v4p0.jed'
        smb         : 'WEDGE400C_SMB_CPLD_v2p4.jed'
        pwr         : 'WEDGE400_2_PWR_CPLD_v2p4.jed'
    oldVersion      :
        fcm         : '4.1'
        scm         : '15.15'
        smb         : '2.2'
        pwr         : '2.3'
    newVersion      :
        fcm         : '4.2'
        scm         : '4.0'
        smb         : '2.4'
        pwr         : '2.4'
BIC:
    name            :  BIC
    hostImageDir    : /home/automation/Auto_Test/automation/FB-Minipack3/autotest/BIC
    isAutoBuild     : false
    imageInfoFile    : none
    localImageDir   : /mnt/data1/BIC
    imageServer     : PC
    oldImage        : 'xg1_snowflake_109.bin'
    newImage        : 'xg1_snowflake_111.bin'
    oldVersion      : 'v1.09'
    newVersion      : 'v1.11'
FPGA                :
    name:  FPGA
    hostImageDir    : /home/automation/Auto_Test/automation/FB-Minipack3/autotest/FPGA
    isAutoBuild     : false
    imageInfoFile    : none
    localImageDir   : '/var/unidiag/firmware'
    imageServer     : PC
    oldImage        : 'mp3_dom_v0.26.bit'
    newImage        : 'mp3_dom_v0.29.bit'
    oldVersion      :
        DOMFPGA1    : '0.26'
        DOMFPGA2    : '0.26'
    newVersion      :
        DOMFPGA1    : '0.29'
        DOMFPGA2    : '0.29'
TH3                 :
    name:  TH3
    hostImageDir    : /home/automation/Auto_Test/automation/FB-Minipack3/autotest/TH3
    isAutoBuild     : false
    imageInfoFile    : none
    localImageDir   : /mnt/data1/TH3
    imageServer     : PC
    oldImage        : 'TH3_PCIE_FW_02_05'
    newImage        : 'pciefw_2.06.bin'
    oldVersion      :
        PCIe FW loader version : '2.5'
        PCIe FW version       : 'D102_08'
    newVersion      :
        PCIe FW loader version : '2.6'
        PCIe FW version       : 'D102_0A'
TH5                 :
    name:  TH5
    hostImageDir    : /home/automation/Auto_Test/automation/FB-Minipack3/autotest/TH5
    isAutoBuild     : false
    imageInfoFile    : none
    localImageDir   : '/var/unidiag/firmware'
    imageServer     : PC
    oldImage        : 'pciefw_d5_m0_v2p11.bin'
    newImage        : 'pciefw_d5_m0_v2p11.bin'
    oldVersion      :
        PCIe FW loader version : '2.11'
        PCIe FW version       : '2_11'
    newVersion      :
        PCIe FW loader version : '2.11'
        PCIe FW version       : '2_11'
BSP                 :
    name:  BSP
    hostImageDir    : /home/automation/Auto_Test/automation/FB-Minipack3/autotest/BSP
    isAutoBuild     : false
    imageInfoFile    : none
    localImageDir   : '/var/unidiag/firmware'
    oldlocalImageDir   : '/root/BSP_v1.4.0'
    newlocalImageDir   : '/root/BSP_v1.4.1'
    imageServer     : PC
    oldImage        : 'fboss-bsp_minipack3_bsp_x86_evt_1.4.0.tar'
    oldImageZip     : 'montblanc_fboss_bsp_dvt1_1.4.0.zip'
    newImage        : 'fboss-bsp_montblanc_fboss_bsp_dvt1_1.4.1.tar'
    newImageZip     : 'montblanc_fboss_bsp_dvt1_1.4.1.zip'
    spiUtilScript   : 'spi-utils.sh'
    weUtilScript    : 'weutil'
    weUtilJson      : 'weutil.json'
    libicuuc        : 'libicuuc.so.67'
    libicudata      : 'libicudata.so.67'
    libicui18n      : 'libicui18n.so.67'
    oldVersion      : 'v1.4.0'
    newVersion      : 'v1.4.1'
OOB                 :
    name:  OOB
    hostImageDir    : /home/automation/Auto_Test/automation/FB-Minipack3/autotest/OOB
    isAutoBuild     : false
    imageInfoFile    : none
    localImageDir   : '/var/unidiag/firmware'
    imageServer     : PC
    oldImage        : 'fru_oob_v1.0'
    newImage        : 'fru_oob_mp3_dvt_v0_1'
    oldVersion      : 'v1.0'
    newVersion      : 'v1.0'
IOB                 :
    name:  IOB
    hostImageDir    : /home/automation/Auto_Test/automation/FB-Minipack3/autotest/FPGA
    isAutoBuild     : false
    imageInfoFile   : none
    localImageDir   : '/var/unidiag/firmware'
    imageServer     : PC
    oldImage        : 'mp3_iob_v0.38.bit'
    newImage        : 'mp3_iob_v0.44.bit'
    oldVersion      : 'v0.38'
    newVersion      : 'v0.44'
SMB                 :
    name:  SMB
    hostImageDir    : '/home/automation/Auto_Test/automation/FB-Minipack3/autotest/CPLD'
    isAutoBuild     : false
    imageInfoFile   : none
    localImageDir   : '/var/unidiag/firmware'
    imageServer     : PC
    oldImage        : 'mp3_smb_v1.3.1.bit'
    newImage        : 'mp3_smb_cpld_v2.0.0_ugd.bit'
    oldVersion      : 'v1.3.1'
    newVersion      : 'v2.0.0'
MCB                 :
    name:  MCB
    hostImageDir    : '/home/automation/Auto_Test/automation/FB-Minipack3/autotest/CPLD'
    isAutoBuild     : false
    imageInfoFile   : none
    localImageDir   : '/var/unidiag/firmware'
    imageServer     : PC
    oldImage        : 'mp3_mcb_v1.3.1.bit'
    newImage        : 'mp3_mcb_cpld_v2.0.0_ugd.bit'
    oldVersion      : 'v1.3.1'
    newVersion      : 'v2.0.1'
SCM                 :
    name:  SCM
    hostImageDir    : '/home/automation/Auto_Test/automation/FB-Minipack3/autotest/CPLD'
    isAutoBuild     : false
    imageInfoFile   : none
    localImageDir   : '/var/unidiag/firmware'
    imageServer     : PC
    oldImage        : 'mp3_scm_v1.3.1.bit'
    newImage        : 'mp3_scm_cpld_v2.0.0_ugd.bit'
    oldVersion              :
        Bridge-IC Version             : 'v1.09'
        Bridge-IC Bootloader Version  : 'v1.10'
        BIOS Version                  : 'XG1_3A07'
        CPLD Version                  : '0x00010032'
        ME Version                    : '3.0.3.45'
        PVCCIN VR Version             : '0x54c8, 0xe9d6'
        DDRAB VR Version              : '0xb41b, 0xe66c'
        P1V05 VR Version              : '0x54c8, 0xe9d6'
    newVersion              :
        Bridge-IC Version             : 'v1.11'
        Bridge-IC Bootloader Version  : 'v1.10'
        BIOS Version                  : 'XG1_3A09'
        CPLD Version                  : '0x00010032'
        ME Version                    : '3.0.3.45'
        PVCCIN VR Version             : '0x54c8, 0xe9d6'
        DDRAB VR Version              : '0xb41b, 0xe66c'
        P1V05 VR Version              : '0x54c8, 0xe9d6'
TPM                 :
    name:  TPM
    hostImageDir    : /home/automation/Auto_Test/automation/FB-Minipack3/autotest/TPM
    isAutoBuild     : false
    imageInfoFile    : none
    localImageDir   : /mnt/data1/TPM
    imageServer     : PC
    oldImage        : 'TPM2_Test_Scripts_for_v3.0.tar.gz'
    newImage        : 'TPM2_Test_Scripts_for_v7.85.tar.gz'
    oldVersion      : '3.0'
    newVersion      : '7.85'
OS                  :
    name:   OS
    hostImageDir    : ''
    isAutoBuild     : false
    imageInfoFile    : none
    localImageDir   : ''
    imageServer     : ''
    oldImage        : ''
    newImage        : ''
    oldVersion      : ''
    newVersion      : '8.1.1911'
KERNEL              :
    name:   KERNEL
    hostImageDir    : ''
    isAutoBuild     : false
    imageInfoFile    : none
    localImageDir   : ''
    imageServer     : ''
    oldImage        : ''
    newImage        : ''
    oldVersion      : ''
    newVersion      : '5.2.21'
PSU                :
    name:  PSU
    hostImageDir    : /home/automation/Auto_Test/automation/FB-Minipack3/autotest/PSU
    isAutoBuild     : false
    imageInfoFile   : none
    localImageDir   : /mnt/data1/PSU
    imageServer     : PC
    oldImage        :
        pri         : 'Delta_Dragon_M_FB1500W_MP_Pri_APP_only_v3.0a_CRC_8264_18Feb2020_JC.bin'
        sec         : 'Delta_Dragon_M_FB1500W_MP_Sec_APP_only_v3.0a_CRC_50B2_18Feb2020_JC.bin'
    newImage        :
        pri         : 'Delta_Dragon_M_FB1500W_MP_Pri_APP_only_v4.0a_CRC_4D57_26Mar2019_HZ.BIN'
        sec         : 'Delta_Dragon_M_FB1500W_MP_Sec_APP_only_v3.2a_CRC_61E9_18Feb2020_JC.bin'
    oldVersion      :
        PRI_FW_VER  : '3.0'
        SEC_FW_VER  : '3.0'
    newVersion      :
        PRI_FW_VER  : '4.0'
        SEC_FW_VER  : '3.2'
DIAG_OS              :
    name:   DIAG_OS
    hostImageDir    : ''
    isAutoBuild     : false
    imageInfoFile    : none
    localImageDir   : ''
    imageServer     : ''
    oldImage        : ''
    newImage        : ''
    oldVersion      : ''
    newVersion      : '3.0.0'
SDK              :
    name:   SDK
    hostImageDir    : /home/automation/Auto_Test/automation/FB-Minipack3/autotest/SDK
    isAutoBuild     : false
    imageInfoFile   : none
    localImageDir   : /root
    imageServer     : PC
    oldImage        : 'gibraltar-sdk-v2.0.0.zip'
    newImage        : 'gibraltar-sdk-v2.0.4.zip'
    oldVersion      : '2.0.0'
    newVersion      : '2.0.4'
    minipack3  :
        bcm_version    : 'sdk-6.5.30'
        PCIe_FW : '20.2'
        serdes_api_version : 'A00409'
        ucode_version : 'D002_0D'
    minerva_janga  :
        PCIe_FW :  '20.0.2'
        broadcom_SDK_version : 'sdk-6.5.29-dnx.1'
        cls_sdk_version : 'v1.2.0'
    minerva_th5 :
        bcm_version    : 'sdk-6.5.29'
        PCIe_FW : '2.11'


CIT                 :
    name:  CIT
    hostImageDir    : /home/automation/Auto_Test/automation/FB-Minipack3/autotest/CIT
    isAutoBuild     : false
    imageInfoFile    : none
    localImageDir   : /mnt/data1/CIT
    imageServer     : PC
    oldImage        : 'cit.tar'
    newImage        : 'cit.tar'
    oldVersion      : ''
    newVersion      : ''
I210              :
    name:   I210
    hostImageDir    : ''
    isAutoBuild     : false
    imageInfoFile    : none
    localImageDir   : ''
    imageServer     : ''
    oldImage        : ''
    newImage        : ''
    oldVersion      : ''
    newVersion      : '3.25'
SEASTONE_BIOS:
        name: SEASTONE_BIOS
        hostImageDir: ''
        isAutoBuild  : false
        imageInfoFile : none
        localImageDir : ''
        imageServer  : ''
        oldImage        : 'Seastone2V2.2.0.0.bin'
        newImage        : 'Seastone2V2.2.0.1.bin'
        oldVersion      : XG1_3A09
        newVersion   :
                clpd_image  : 'Seastone2_V2_EVT_B_V1.6_C_V0.7_SW1_V1.0_SW2_V1.0.vme'
                bmc_image  : 'R4039-DS3000-2.00.00.ima'
                memtest_image :  'memtest86-usb.img'
                Afuefix64_file : 'AfuEfix64.efi'
                afulnx_64_image : 'afulnx_64'
                stress_file : 'stress'
                cel_diag_image: 'cel_diag-seastone2v2.v2.0.0-x86.deb'

DIAG              :
    name:   DIAG
    hostImageDir    : /home/automation/Auto_Test/automation/FB-Minipack3/autotest/DIAG
    isAutoBuild     : false
    imageInfoFile   : ImageInfo.yaml
    localImageDir   : /home
    imageServer     : PC
    oldImage        : ''
    newImage        : ''
    oldVersion      : '1.2.12'
    newVersion      : '1.2.12'
    mp3_version:
        bmc_image  : 'R4039-DS3000-2.00.00.ima'
        memtest_image :  'memtest86-usb.img'
        Afuefix64_file : 'AfuEfix64.efi'
        afulnx_64_image : 'afulnx_64'
        stress_file : 'stress'
        cel_diag_image: 'cel_diag-seastone2v2.v2.0.0-x86.deb'
        BIOS: 'NL302'
        BMC:  'montblanc-v0.30 \(master\)'
        #I210: '3.30, 0x80000774'
        #I210: '3.30, 0x8000079f'
        I210: ''
        SDK:  'CLS_SDK_APP_2.0.0'
        BSP:  'v1.4.1'
        UDEV: 'v1.1.0'
        OS:   'v1.1.0'
        IOB_FPGA : 'v0.44'
        DOM1_FPGA : 'v0.36'
        DOM2_FPGA : 'v0.36'
        SCM_CPLD : 'v2.0.0'
        SMB_CPLD : 'v2.0.0'
        MCB_CPLD : 'v2.0.0'
        PN: 'R3214-G0009-01'
        TH5_Switch: '20.2'
        #PN: 'R3214-F9002-01'
        SN: 'A091323180070'
        #SN: 'F501323160003'
        #th5_image: 'fw_pciefw_d5_m0_V2p11.bin'
        th5_image: 'fw_pcie_20.bin'
        #smb_image: 'fw_smb_cpld_v1.3.1.bit'
        smb_image: 'fw_smb_cpld_v2.0.0_ugd.bit'
        
        #scm_image: 'fw_scm_cpld_v1.3.1.bit'
        scb_image: 'fw_scb_cpld_v2.0.0_ugd.bit'
        
        #mcb_image:  'fw_mcb_cpld_v1.3.1.bit'
        mcb_image: 'fw_mcb_cpld_v2.0.0_ugd.bit'
        
        dom_image: 'fw_dom_v0.36.bit'
        iob_image: 'fw_iob_v0.44.bit'
        diagNewImage: 'montblanc_unidiag_dvt_x86_1.2.12'
        mcb_cpld_file: 'fw_mcb_cpld_v1.3.1.bit'
        scm_cpld_file: 'fw_scm_cpld_v1.3.1.bit'
        smb_clpd_file: 'fw_smb_cpld_v1.3.1.bit'
        
        iob_fpga_file: 'fw_iob_v0.38.bit'  
        #dom_flash_file: 'fw_dom_v0.29.bit'
        dom_flash_file: 'fw_dom_v0.36.bit'

        
minerva_version:
        bmc_image  : 'R4039-DS3000-2.00.00.ima'
        memtest_image :  'memtest86-usb.img'
        Afuefix64_file : 'AfuEfix64.efi'
        afulnx_64_image : 'afulnx_64'
        stress_file : 'stress'
        cel_diag_image: 'cel_diag-seastone2v2.v2.0.0-x86.deb'
        BIOS: 'NL204'
        BMC:  'janga-v0.20 \(master\)'
        I210: 'v3.30, 0x80000774'
        SDK:  'v1.2.0'
        BSP:  'v0.0.7'
        UDEV: 'v1.0.4'
        OS:   'v1.0.4'
        Platform:   'Janga'
        IOB_FPGA : 'v0.35'
        DOM_FPGA : 'v0.26'
        SMB_CPLD1 : 'v1.3.0'
        SMB_CPLD2 : 'v1.3.0'
        PWR_CPLD : 'v1.3.0'
        PN: 'R4054-G0002-02'
        SN: 'GM22223450009'
        th5_image: 'fw_pciefw_d5_m0_V2p11.bin'
        smb_image: 'fw_smb_cpld_v1.3.1.bit'
        scm_image: 'fw_scm_cpld_v1.3.1.bit'
        mcb_image:  'fw_mcb_cpld_v1.3.1.bit'
                
                
MEM_TEST            :
    name:   MEM_TEST
    hostImageDir    : /home/automation/Auto_Test/automation/FB-Minipack3/autotest/BMC
    isAutoBuild     : false
    imageInfoFile   : ''
    localImageDir   : /mnt/data/MEM_TEST
    imageServer     : PC
    oldImage        : memtester
    newImage        : memtester
    oldVersion      : ''
    newVersion      : ''
        
      






UDEV              :
    name:  UDEV
    hostImageDir    : ''
    isAutoBuild     : false
    imageInfoFile    : none
    localImageDir   : ''
    imageServer     : ''
    oldImage        : ''
    newImage        : ''
    oldVersion      : 'v1.1.0'
    newVersion      : 'v1.1.1'

