###############################################################################
# LEGALESE:   "Copyright (C) 2019-2020, Celestica Corp. All rights reserved." #
#                                                                             #
# This source code is confidential, proprietary, and contains trade           #
# secrets that are the sole property of Celestica Corp.                       #
# Copy and/or distribution of this source code or disassembly or reverse      #
# engineering of the resultant object code are strictly forbidden without     #
# the written consent of Celestica Corp.                                      #
#                                                                             #
###############################################################################

### for Wedge400C test

SCM_EEPROM_DEFAULT:
    product_name                    : 'WEDGE400-SCM'
    eeprom_location_on_fabric       : 'SCM'

OOB:
    magic_word                      : '0xFBFB'
    format_version                  : '0x4'
    product_name                    : 'MINIPACK3-SCM'
    top_level_product_part_number   : '30-000161'
    system_assembly_part_number     : '30-000163'
    facebook_pcba_part_number       : '132-000162-01'
    facebook_pcb_part_number        : '131-000129-01'
    odm_pcba_part_number            : 'R3214-F9002-01'
    odm_pcba_serial_number          : 'F501323160003'
    product_production_state        : '1'
    product_version                 : '0'
    product_sub_version             : '1'
    product_serial_number           : 'F501323160003'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20240625'
    pcb_manufacturer                : 'GCE'
    assembled_at                    : 'CTH'
    local_mac_address               : '00:00:00:95:FD:CA'
    extended_mac_address_base       : '00:00:00:95:FD:CC'
    extended_mac_address_size       : '0x8a'
    eeprom_location_on_fabric       : 'SCM'
    crc16                           : '0xf1a7'

SCM_EEPROM_TEST:
    magic_word                      : '0xFBFB'
    format_version                  : '0x4'
    product_name                    : 'MINIPACK3-SCM'
    top_level_product_part_number   : '30-000161'
    system_assembly_part_number     : '30-000163'
    facebook_pcba_part_number       : '132-000162-01'
    facebook_pcb_part_number        : '131-000129-01'
    odm_pcba_part_number            : 'R3214-F9002-01'
    odm_pcba_serial_number          : 'F501323160003'
    product_production_state        : '1'
    product_version                 : '0'
    product_sub_version             : '1'
    product_serial_number           : 'F501323160003'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20240625'
    pcb_manufacturer                : 'GCE'
    assembled_at                    : 'CTH'
    local_mac_address               : '00:00:00:95:FD:CA'
    extended_mac_address_base       : '00:00:00:95:FD:CC'
    extended_mac_address_size       : '0x8a'
    eeprom_location_on_fabric       : 'SCM'
    crc16                           : '0xf1a7'

SCM_EEPROM_TEST2:
    magic_word                      : '0xFBFB'
    format_version                  : '0x3'
    product_name                    : 'WEDGE400-SCM'
    top_level_product_part_number   : '1111'
    system_assembly_part_number     : '19001111'
    facebook_pcba_part_number       : '13200011111'
    facebook_pcb_part_number        : '13100001111'
    odm_pcba_part_number            : 'R1149G001111'
    odm_pcba_serial_number          : 'G021119071111'
    product_production_state        : '1'
    product_version                 : '1'
    product_sub_version             : '1'
    product_serial_number           : 'F0C1RYYWW1111'
    product_asset_tag               : 'NA'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20200602'
    pcb_manufacturer                : 'WUS'
    assembled_at                    : 'CLS'
    local_mac_address               : '000000001111'
    extended_mac_address_base       : '000000001111'
    extended_mac_address_size       : '0'
    eeprom_location_on_fabric       : 'SCM'

SMB_EEPROM_DEFAULT:
    product_name                    : 'WEDGE400C-SMB'
    eeprom_location_on_fabric       : 'SMB'

SMB_EEPROM_TEST:
    magic_word                      : '0xFBFB'
    format_version                  : '0x4'
    product_name                    : 'TAHAN'
    top_level_product_part_number   : '20-100025'
    system_assembly_part_number     : '19-100062'
    facebook_pcba_part_number       : '132-100010'
    facebook_pcb_part_number        : '131-100008'
    odm_pcba_part_number            : 'R4054-G0002-02'
    odm_pcba_serial_number          : 'GM22123390007'
    product_production_state        : '1'
    product_version                 : '0'
    product_sub_version             : '0'
    product_serial_number           : 'FM12123410036'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20241031'
    pcb_manufacturer                : 'WUS'
    assembled_at                    : 'CTH'
    local_mac_address               : '00:00:00:00:FD:CA'
    extended_mac_address_base       : '00:00:00:00:FD:CC'
    extended_mac_address_size       : '0x8a'
    eeprom_location_on_fabric       : 'SMB'
    crc16                           : '0xf2a7'

COME_EEPROM_TEST:
    magic_word                      : '0xFBFB'
    format_version                  : '0x4'
    product_name                    : 'TAHAN'
    top_level_product_part_number   : '20-100025'
    system_assembly_part_number     : '19-100062'
    facebook_pcba_part_number       : '132-100010'
    facebook_pcb_part_number        : '131-100008'
    odm_pcba_part_number            : 'R4054-G0002-02'
    odm_pcba_serial_number          : 'GM22123390007'
    product_production_state        : '1'
    product_version                 : '1'
    product_sub_version             : '0'
    product_serial_number           : 'FM12123410036'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20201031'
    pcb_manufacturer                : 'WUS'
    assembled_at                    : 'CTH'
    local_mac_address               : '00:00:00:00:FD:CB'
    extended_mac_address_base       : '00:00:00:00:FD:CD'
    extended_mac_address_size       : '0x8a'
    eeprom_location_on_fabric       : 'COME'
    crc16                           : '0xf2a7'

SMB_EEPROM_TEST2:
    magic_word                      : '0xFBFB'
    format_version                  : '0x3'
    product_name                    : 'WEDGE400C-SMB'
    top_level_product_part_number   : '20001111'
    system_assembly_part_number     : '1111'
    facebook_pcba_part_number       : '13200001111'
    facebook_pcb_part_number        : '13100001111'
    odm_pcba_part_number            : 'R1149G001111'
    odm_pcba_serial_number          : 'G012119201111'
    product_production_state        : '1'
    product_version                 : '1'
    product_sub_version             : '1'
    product_serial_number           : 'F0A211911111'
    product_asset_tag               : '5851111'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20200602'
    pcb_manufacturer                : 'WUS'
    assembled_at                    : 'CLS'
    local_mac_address               : '00E0ECDCA4C9'
    extended_mac_address_base       : 'AABBCCFFEEA9'
    extended_mac_address_size       : '143'
    eeprom_location_on_fabric       : 'SMB'

MCB_EEPROM_TEST:
    magic_word                      : '0xFBFB'
    format_version                  : '0x4'
    product_name                    : 'MINIPACK3-MCB'
    top_level_product_part_number   : '32-000161'
    system_assembly_part_number     : '32-000163'
    facebook_pcba_part_number       : '131-000162-01'
    facebook_pcb_part_number        : '132-000129-01'
    odm_pcba_part_number            : 'R3314-F9002-01'
    odm_pcba_serial_number          : 'F511323160003'
    product_production_state        : '1'
    product_version                 : '0'
    product_sub_version             : '1'
    product_serial_number           : 'F511323160003'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20240325'
    pcb_manufacturer                : 'GCE'
    assembled_at                    : 'CTH'
    local_mac_address               : '00:00:00:95:FF:CA'
    extended_mac_address_base       : '00:00:00:95:FF:CC'
    extended_mac_address_size       : '0x8a'
    eeprom_location_on_fabric       : 'MCB'
    crc16                           : '0xf1a7'

FCM_EEPROM_DEFAULT:
    product_name                    : 'WEDGE400-FCM'
    eeprom_location_on_fabric       : 'FCM'

FCM_EEPROM_TEST:
    magic_word                      : '0xFBFB'
    format_version                  : '0x3'
    product_name                    : 'WEDGE400-FCM'
    top_level_product_part_number   : '0000'
    system_assembly_part_number     : '0000'
    facebook_pcba_part_number       : '13200000000'
    facebook_pcb_part_number        : '13100000000'
    odm_pcba_part_number            : 'R1149G000000'
    odm_pcba_serial_number          : 'G031119070000'
    product_production_state        : '0'
    product_version                 : '0'
    product_sub_version             : '0'
    product_serial_number           : 'NA'
    product_asset_tag               : 'NA'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20200601'
    pcb_manufacturer                : 'WUS'
    assembled_at                    : 'CLS'
    local_mac_address               : '000000000000'
    extended_mac_address_base       : '000000000000'
    extended_mac_address_size       : '0'
    eeprom_location_on_fabric       : 'FCM'

FCM_EEPROM_TEST2:
    magic_word                      : '0xFBFB'
    format_version                  : '0x3'
    product_name                    : 'WEDGE400-FCM'
    top_level_product_part_number   : '1111'
    system_assembly_part_number     : '1111'
    facebook_pcba_part_number       : '13200001111'
    facebook_pcb_part_number        : '13100001111'
    odm_pcba_part_number            : 'R1149G001111'
    odm_pcba_serial_number          : 'G031119071111'
    product_production_state        : '1'
    product_version                 : '1'
    product_sub_version             : '1'
    product_serial_number           : 'NA'
    product_asset_tag               : 'NA'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20200602'
    pcb_manufacturer                : 'WUS'
    assembled_at                    : 'CLS'
    local_mac_address               : '000000000000'
    extended_mac_address_base       : '000000000000'
    extended_mac_address_size       : '0'
    eeprom_location_on_fabric       : 'FCM'

FAN_EEPROM_DEFAULT:
    product_name                    : 'WEDGE400-FAN'
    eeprom_location_on_fabric       : 'FAN'

FAN_EEPROM_TEST:
    magic_word                      : '0xFBFB'
    format_version                  : '0x3'
    product_name                    : 'WEDGE400-FAN'
    top_level_product_part_number   : 'NA'
    system_assembly_part_number     : '05000000'
    facebook_pcba_part_number       : '13200000000'
    facebook_pcb_part_number        : '13100000000'
    odm_pcba_part_number            : 'R1018G000000'
    odm_pcba_serial_number          : 'G031119070000'
    product_production_state        : '0'
    product_version                 : '0'
    product_sub_version             : '0'
    product_serial_number           : 'R064219160000'
    product_asset_tag               : 'NA'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20200601'
    pcb_manufacturer                : 'WUS'
    assembled_at                    : 'CLS'
    local_mac_address               : '000000000000'
    extended_mac_address_base       : '000000000000'
    extended_mac_address_size       : '0'
    eeprom_location_on_fabric       : 'FAN'

FAN_EEPROM_TEST2:
    magic_word                      : '0xFBFB'
    format_version                  : '0x3'
    product_name                    : 'WEDGE400-FAN'
    top_level_product_part_number   : 'NA'
    system_assembly_part_number     : '05001111'
    facebook_pcba_part_number       : '13200001111'
    facebook_pcb_part_number        : '13100001111'
    odm_pcba_part_number            : 'R1018G001111'
    odm_pcba_serial_number          : 'G031119071111'
    product_production_state        : '1'
    product_version                 : '1'
    product_sub_version             : '1'
    product_serial_number           : 'R064219161111'
    product_asset_tag               : 'NA'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20200602'
    pcb_manufacturer                : 'WUS'
    assembled_at                    : 'CLS'
    local_mac_address               : '000000000000'
    extended_mac_address_base       : '000000000000'
    extended_mac_address_size       : '0'
    eeprom_location_on_fabric       : 'FAN'

PEM_EEPROM_DEFAULT:
    product_name                    : 'WEDGE400-PEM'
    eeprom_location_on_fabric       : 'PEM'

PEM_EEPROM_TEST:
    magic_word                      : '0xFBFB'
    format_version                  : '0x3'
    product_name                    : 'WEDGE400-PEM'
    top_level_product_part_number   : 'NA'
    system_assembly_part_number     : '03-000000'
    facebook_pcba_part_number       : '13200000000'
    facebook_pcb_part_number        : '13100000000'
    odm_pcba_part_number            : 'R1149G0000000'
    odm_pcba_serial_number          : 'G083219340000'
    product_production_state        : '2'
    product_version                 : '0'
    product_sub_version             : '0'
    product_serial_number           : 'S083219360000'
    product_asset_tag               : 'NA'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20190905'
    pcb_manufacturer                : 'WUS'
    assembled_at                    : 'CTH'
    local_mac_address               : '000000000000'
    extended_mac_address_base       : '000000000000'
    extended_mac_address_size       : '0'
    eeprom_location_on_fabric       : 'PEM'

PEM_EEPROM_TEST2:
    magic_word                      : '0xFBFB'
    format_version                  : '0x3'
    product_name                    : 'WEDGE400-PEM'
    top_level_product_part_number   : 'NA'
    system_assembly_part_number     : '03-001111'
    facebook_pcba_part_number       : '13200001111'
    facebook_pcb_part_number        : '13100001111'
    odm_pcba_part_number            : 'R1149G0001111'
    odm_pcba_serial_number          : 'G083219341111'
    product_production_state        : '2'
    product_version                 : '0'
    product_sub_version             : '0'
    product_serial_number           : 'S083219361111'
    product_asset_tag               : 'NA'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20190905'
    pcb_manufacturer                : 'WUS'
    assembled_at                    : 'CTH'
    local_mac_address               : '000000000000'
    extended_mac_address_base       : '000000000000'
    extended_mac_address_size       : '0'
    eeprom_location_on_fabric       : 'PEM'

HOTSWAP_EEPROM_TEST:
    '0x20' : '0x3a'
    '0x31' : '0x35'

HOTSWAP_EEPROM_TEST2:
    '0x20' : '0x3c'
    '0x31' : '0x37'
