###############################################################################
# LEGALESE:   "Copyright (C) 2019-2020, Celestica Corp. All rights reserved." #
#                                                                             #
# This source code is confidential, proprietary, and contains trade           #
# secrets that are the sole property of Celestica Corp.                       #
# Copy and/or distribution of this source code or disassembly or reverse      #
# engineering of the resultant object code are strictly forbidden without     #
# the written consent of Celestica Corp.                                      #
#                                                                             #
###############################################################################
powerCycler1:
    userName  : apc
    password  : 'apc'
    product   : powercycler
    managementIP : 10.204.125.93
    managementPort : '23'
    managementPrompt : 'apc>'
    platformType : Schneider Electric

powerCycler2:
    userName  : apc
    password  : 'apc'
    product   : powercycler
    managementIP : 10.204.125.121
    managementPort : '23'
    managementPrompt : 'apc>'
    platformType : Schneider Electric
