###############################################################################
# LEGALESE:   "Copyright (C) 2019-2020, Celestica Corp. All rights reserved." #
#                                                                             #
# This source code is confidential, proprietary, and contains trade           #
# secrets that are the sole property of Celestica Corp.                       #
# Copy and/or distribution of this source code or disassembly or reverse      #
# engineering of the resultant object code are strictly forbidden without     #
# the written consent of Celestica Corp.                                      #
#                                                                             #
###############################################################################

### for Cloudripper test

SCM_EEPROM_DEFAULT:
    product_name                    : 'CLOUDRIPPER-SCM'
    eeprom_location_on_fabric       : 'SCM'

SCM_EEPROM_TEST:
    magic_word                      : '0xFBFB'
    format_version                  : '0x3'
    product_name                    : 'CLOUDRIPPER-SCM'
    top_level_product_part_number   : '00000000'
    system_assembly_part_number     : '19000000'
    facebook_pcba_part_number       : '13200010000'
    facebook_pcb_part_number        : '13100000000'
    odm_pcba_part_number            : 'R1149G000000'
    odm_pcba_serial_number          : 'G021119070000'
    product_production_state        : '1'
    product_version                 : '1'
    product_sub_version             : '1'
    product_serial_number           : 'F0C1RYYWW0000'
    product_asset_tag               : 'NA'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20200602'
    pcb_manufacturer                : 'WUS'
    assembled_at                    : 'CLS'
    local_mac_address               : '000000000000'
    extended_mac_address_base       : '000000000000'
    extended_mac_address_size       : '0'
    eeprom_location_on_fabric       : 'SCM'

SCM_EEPROM_TEST2:
    magic_word                      : '0xFBFB'
    format_version                  : '0x3'
    product_name                    : 'CLOUDRIPPER-SCM'
    top_level_product_part_number   : '1111'
    system_assembly_part_number     : '19001111'
    facebook_pcba_part_number       : '13200011111'
    facebook_pcb_part_number        : '13100001111'
    odm_pcba_part_number            : 'R1149G001111'
    odm_pcba_serial_number          : 'G021119071111'
    product_production_state        : '1'
    product_version                 : '1'
    product_sub_version             : '1'
    product_serial_number           : 'F0C1RYYWW1111'
    product_asset_tag               : 'NA'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20200602'
    pcb_manufacturer                : 'WUS'
    assembled_at                    : 'CLS'
    local_mac_address               : '000000001111'
    extended_mac_address_base       : '000000001111'
    extended_mac_address_size       : '0'
    eeprom_location_on_fabric       : 'SCM'

SMB_EEPROM_DEFAULT:
    product_name                    : 'CLOUDRIPPER-SMB'
    eeprom_location_on_fabric       : 'SMB'

SMB_EEPROM_TEST:
    magic_word                      : '0xFBFB'
    format_version                  : '0x3'
    product_name                    : 'CLOUDRIPPER-SMB'
    top_level_product_part_number   : '20000000'
    system_assembly_part_number     : '0000'
    facebook_pcba_part_number       : '13200000000'
    facebook_pcb_part_number        : '13100000000'
    odm_pcba_part_number            : 'R1149G000000'
    odm_pcba_serial_number          : 'G012119200000'
    product_production_state        : '0'
    product_version                 : '0'
    product_sub_version             : '0'
    product_serial_number           : 'F0A211910000'
    product_asset_tag               : '5850000'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20200601'
    pcb_manufacturer                : 'WUS'
    assembled_at                    : 'CLS'
    local_mac_address               : '00E0ECDCA4C9'
    extended_mac_address_base       : 'AABBCCFFEEA9'
    extended_mac_address_size       : '143'
    eeprom_location_on_fabric       : 'SMB'

SMB_EEPROM_TEST2:
    magic_word                      : '0xFBFB'
    format_version                  : '0x3'
    product_name                    : 'CLOUDRIPPER-SMB'
    top_level_product_part_number   : '20001111'
    system_assembly_part_number     : '1111'
    facebook_pcba_part_number       : '13200001111'
    facebook_pcb_part_number        : '13100001111'
    odm_pcba_part_number            : 'R1149G001111'
    odm_pcba_serial_number          : 'G012119201111'
    product_production_state        : '1'
    product_version                 : '1'
    product_sub_version             : '1'
    product_serial_number           : 'F0A211911111'
    product_asset_tag               : '5851111'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20200602'
    pcb_manufacturer                : 'WUS'
    assembled_at                    : 'CLS'
    local_mac_address               : '00E0ECDCA4C9'
    extended_mac_address_base       : 'AABBCCFFEEA9'
    extended_mac_address_size       : '143'
    eeprom_location_on_fabric       : 'SMB'

FCM_EEPROM_DEFAULT:
    product_name                    : 'CLOUDRIPPER-FCM'
    eeprom_location_on_fabric       : 'FCM'

FCM_EEPROM_TEST:
    magic_word                      : '0xFBFB'
    format_version                  : '0x3'
    product_name                    : 'CLOUDRIPPER-FCM'
    top_level_product_part_number   : '0000'
    system_assembly_part_number     : '0000'
    facebook_pcba_part_number       : '13200000000'
    facebook_pcb_part_number        : '13100000000'
    odm_pcba_part_number            : 'R1149G000000'
    odm_pcba_serial_number          : 'G031119070000'
    product_production_state        : '0'
    product_version                 : '0'
    product_sub_version             : '0'
    product_serial_number           : 'NA'
    product_asset_tag               : 'NA'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20200601'
    pcb_manufacturer                : 'WUS'
    assembled_at                    : 'CLS'
    local_mac_address               : '000000000000'
    extended_mac_address_base       : '000000000000'
    extended_mac_address_size       : '0'
    eeprom_location_on_fabric       : 'FCM'

FCM_EEPROM_TEST2:
    magic_word                      : '0xFBFB'
    format_version                  : '0x3'
    product_name                    : 'CLOUDRIPPER-FCM'
    top_level_product_part_number   : '1111'
    system_assembly_part_number     : '1111'
    facebook_pcba_part_number       : '13200001111'
    facebook_pcb_part_number        : '13100001111'
    odm_pcba_part_number            : 'R1149G001111'
    odm_pcba_serial_number          : 'G031119071111'
    product_production_state        : '1'
    product_version                 : '1'
    product_sub_version             : '1'
    product_serial_number           : 'NA'
    product_asset_tag               : 'NA'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20200602'
    pcb_manufacturer                : 'WUS'
    assembled_at                    : 'CLS'
    local_mac_address               : '000000000000'
    extended_mac_address_base       : '000000000000'
    extended_mac_address_size       : '0'
    eeprom_location_on_fabric       : 'FCM'

FAN_EEPROM_DEFAULT:
    product_name                    : 'CLOUDRIPPER-FAN'
    eeprom_location_on_fabric       : 'FAN'

FAN_EEPROM_TEST:
    magic_word                      : '0xFBFB'
    format_version                  : '0x3'
    product_name                    : 'CLOUDRIPPER-FAN'
    top_level_product_part_number   : 'NA'
    system_assembly_part_number     : '05000000'
    facebook_pcba_part_number       : '13200000000'
    facebook_pcb_part_number        : '13100000000'
    odm_pcba_part_number            : 'R1018G000000'
    odm_pcba_serial_number          : 'G031119070000'
    product_production_state        : '0'
    product_version                 : '0'
    product_sub_version             : '0'
    product_serial_number           : 'R064219160000'
    product_asset_tag               : 'NA'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20200601'
    pcb_manufacturer                : 'WUS'
    assembled_at                    : 'CLS'
    local_mac_address               : '000000000000'
    extended_mac_address_base       : '000000000000'
    extended_mac_address_size       : '0'
    eeprom_location_on_fabric       : 'FAN'

FAN_EEPROM_TEST2:
    magic_word                      : '0xFBFB'
    format_version                  : '0x3'
    product_name                    : 'CLOUDRIPPER-FAN'
    top_level_product_part_number   : 'NA'
    system_assembly_part_number     : '05001111'
    facebook_pcba_part_number       : '13200001111'
    facebook_pcb_part_number        : '13100001111'
    odm_pcba_part_number            : 'R1018G001111'
    odm_pcba_serial_number          : 'G031119071111'
    product_production_state        : '1'
    product_version                 : '1'
    product_sub_version             : '1'
    product_serial_number           : 'R064219161111'
    product_asset_tag               : 'NA'
    system_manufacturer             : 'CLS'
    system_manufacturing_date       : '20200602'
    pcb_manufacturer                : 'WUS'
    assembled_at                    : 'CLS'
    local_mac_address               : '000000000000'
    extended_mac_address_base       : '000000000000'
    extended_mac_address_size       : '0'
    eeprom_location_on_fabric       : 'FAN'
