###############################################################################
# LEGALESE:   "Copyright (C) 2019-2020, Celestica Corp. All rights reserved." #
#                                                                             #
# This source code is confidential, proprietary, and contains trade           #
# secrets that are the sole property of Celestica Corp.                       #
# Copy and/or distribution of this source code or disassembly or reverse      #
# engineering of the resultant object code are strictly forbidden without     #
# the written consent of Celestica Corp.                                      #
#                                                                             #
###############################################################################
minipack2_10002 :
    name    : minipack2_10002
    os      : sonic
    deviceType      : DUT
    consoleIP       : 192.168.0.240
    consolePort     : 10002
    bmcConsoleIP     : 192.168.0.240
    bmcConsolePort   : 10002
    # for wedge400, switch to BMC: ctrl+l and x, switch to CPU: execute sol.sh
    keysSwitchToCpu: ['sol.sh \r\n']
    keysSwitchToBmc: ["\x0c", "x"]
    userName        : admin
    password        : admin
    rootUserName    : root
    rootPassword    : '11'
    bmcUserName:  root
    bmcPassword: '0penBmc'
    managementIP    : 192.168.0.34
    managementMask  : 255.255.254.0
    platform         : facebook
    managementInterface : eth0
    powerCycler     : powerCycler1
    powerCyclerPort : 15
    poeTesters      : ['poeTester1', 'poeTester2']
    epsList          : ['eps1', 'eps2']
    promptOnie      : 'ONIE:/'
    promptDiagOS    : 'root@fb8396dd '
    promptGrub      : 'Grub'
    promptBmc       : 'root@bmc-oob:'
    loginPromptDiagOS : 'fb8396dd login'
    loginPromptBmc  : 'bmc-oob.? login:'
minipack2_10003 :
    name    : minipack2_10003
    os      : sonic
    deviceType      : DUT
    consoleIP       : 192.168.0.240
    consolePort     : 10003
    bmcConsoleIP     : 192.168.0.240
    bmcConsolePort   : 10003
    # for wedge400, switch to BMC: ctrl+l and x, switch to CPU: execute sol.sh
    keysSwitchToCpu: ['sol.sh \r\n']
    keysSwitchToBmc: ["\x0c", "x"]
    userName        : admin
    password        : admin
    rootUserName    : root
    rootPassword    : '11'
    bmcUserName:  root
    bmcPassword: '0penBmc'
    managementIP    : 192.168.0.34
    managementMask  : 255.255.254.0
    platform         : facebook
    managementInterface : eth0
    powerCycler     : powerCycler1
    powerCyclerPort : 15
    poeTesters      : ['poeTester1', 'poeTester2']
    epsList          : ['eps1', 'eps2']
    promptOnie      : 'ONIE:/'
    promptDiagOS    : 'root@fb8396fe '
    promptGrub      : 'Grub'
    promptBmc       : 'root@bmc-oob:'
    loginPromptDiagOS : 'fb8396fe login'
    loginPromptBmc  : 'bmc-oob.? login:'
minipack2_10005 :
    name    : minipack2_10005
    os      : sonic
    deviceType      : DUT
    consoleIP       : 192.168.0.240
    consolePort     : 10005
    bmcConsoleIP     : 192.168.0.240
    bmcConsolePort   : 10005
    # for wedge400, switch to BMC: ctrl+l and x, switch to CPU: execute sol.sh
    keysSwitchToCpu: ['sol.sh \r\n']
    keysSwitchToBmc: ["\x0c", "x"]
    userName        : admin
    password        : admin
    rootUserName    : root
    rootPassword    : '11'
    bmcUserName:  root
    bmcPassword: '0penBmc'
    managementIP    : 192.168.0.33
    managementMask  : 255.255.254.0
    platform         : facebook
    managementInterface : eth0
    powerCycler     : powerCycler1
    powerCyclerPort : 15
    poeTesters      : ['poeTester1', 'poeTester2']
    epsList          : ['eps1', 'eps2']
    promptOnie      : 'ONIE:/'
    promptDiagOS    : 'root@fb971d4a '
    promptGrub      : 'Grub'
    promptBmc       : 'root@.*:'
    loginPromptDiagOS : 'fb971d4a login'
    loginPromptBmc  : 'login:'
minipack2_10006 :
    name    : minipack2_10006
    os      : sonic
    deviceType      : DUT
    consoleIP       : 192.168.0.240
    consolePort     : 10006
    bmcConsoleIP     : 192.168.0.240
    bmcConsolePort   : 10006
    # for wedge400, switch to BMC: ctrl+l and x, switch to CPU: execute sol.sh
    keysSwitchToCpu: ['sol.sh \r\n']
    keysSwitchToBmc: ["\x0c", "x"]
    userName        : admin
    password        : admin
    rootUserName    : root
    rootPassword    : '11'
    bmcUserName:  root
    bmcPassword: '0penBmc'
    managementIP    : 192.168.0.33
    managementMask  : 255.255.254.0
    platform         : facebook
    managementInterface : eth0
    powerCycler     : powerCycler1
    powerCyclerPort : 15
    poeTesters      : ['poeTester1', 'poeTester2']
    epsList          : ['eps1', 'eps2']
    promptOnie      : 'ONIE:/'
    promptDiagOS    : 'root@fb971d68 '
    promptGrub      : 'Grub'
    promptBmc       : 'root@.*:'
    loginPromptDiagOS : 'fb971d68 login'
    loginPromptBmc  : 'login:'
PC :
  name            : PC
  deviceType      : server
  platform        : ubuntu
  username        : svt
  password        : '123456'
  rootUserName    : svt
  rootPassword    : '123456'
  scpUsername     : 'svt'
  scpPassword     : '123456'
  managementIP    : 192.168.0.4
  managementIPV6  : '2001:db8:0:2::2'
  staticIPV6      : 'fe80::ba2a:72ff:fed7:f014'
  prompt          : 'svt-NF5270M3'
JENKINS :
  name            : JENKINS
  deviceType      : server
  platform        : ubuntu
  username        : svt
  password        : '123456'
  rootUserName    : svt
  rootPassword    : '123456'
  scpUsername     : 'svt'
  scpPassword     : '123456'
  managementIP    : 192.168.0.4
  managementIPV6  : '2001:db8:0:1::2'
  staticIPV6      : 'fe80::ba2a:72ff:fed7:f014'
  prompt          : 'svt-NF5270M3'
platforms:
    facebook:
        email_group : [xiaoqwa@celestica.com]
    alibaba:
        email_group : [xiaoqwa@celestica.com]
